url: "http://handbook.boxproducts.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Box Products" # the name of your site, e.g. ACME Corp.
